import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ConfigProvider, App as AntApp } from 'antd';
import NotificationProvider from './notification-provider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Helppeople Prueba técnica',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider>
          <AntApp>
            <NotificationProvider>{children}</NotificationProvider>
          </AntApp>
        </ConfigProvider>
      </body>
    </html>
  );
}
